added configuration to skip saving pinned tabs
dwarvesf/session-buddy pull request #11
Opened 2020-09-26 13:56 UTC by kevinpapst

#### What's this PR do?

This PR adds a new preference setting "Ignore pinned tabs".

When activated: pinned tabs will not be added to the list of URLs when saving a session.

The main logic that was added (besides the new preference) is the following if:
```swift
                    tab.getContainingWindow(completionHandler: { win in
                        let ignoreTab = Preferences.ignorePinnedTabs && win == nil;
                        if !ignoreTab {
                           // normal saving logic
                        }
                    });
```

Discussion on how to detect pinned tabs:
- https://developer.apple.com/forums/thread/123120
- https://stackoverflow.com/questions/63509871/check-if-tab-page-is-pinned-in-safari-app-extension

Here is a screenshot of the relevant method in `SFSafariTab` class:
<img width="658" alt="Bildschirmfoto 2020-09-26 um 15 44 26" src="https://user-images.githubusercontent.com/533162/94342131-2af2d980-000f-11eb-98f8-97f0b6c46dd6.png">

This is my first take on a Swift project (normally PHP is my dev language) so please review with care. I am especially unsure about the `.xib` file which I didn't edit manually. And sorry for the unrelated white space changes, I opened the file with another IDE and didn't recognize them before seeing the diff here at GH...

#### What are the relevant Git tickets?

Fixes https://github.com/dwarvesf/session-buddy/issues/10

#### Screenshots (if appropriate)

<img width="343" alt="Bildschirmfoto 2020-09-26 um 15 46 53" src="https://user-images.githubusercontent.com/533162/94342171-82914500-000f-11eb-836b-8f0dc8899a41.png">

2020-09-26 16:32 UTC, phucledien commented
well, everything is okay except for one little thing, I think you should check it. 

Thank you for your PR and happy hacktoberfest =]

2020-09-26 16:32 UTC, phucledien requested changes
well, everything is okay except for one little thing, I think you should check it.

Thank you for your PR and happy hacktoberfest =]

2020-09-26 16:32 UTC, phucledien commented on SessionBuddy Extension/SafariExtensionHandler.swift
> +                self.saveLatestSession();
In Swift, we don't need to put the `;` at the end of the statement. So you should remove it here 👍

2020-09-26 18:18 UTC, kevinpapst commented on SessionBuddy Extension/SafariExtensionHandler.swift
> +                self.saveLatestSession();
Right, I don't even know how it slipped in there, must be muscle memory from the languages I normally use 😁 

Do you want me to remove the semicolon from the lines I added as well? Like here:
```
let ignoreTab = Preferences.ignorePinnedTabs && win == nil;
```

2020-09-26 18:31 UTC, kevinpapst commented
Okay, removed the whitespace changes and all semicolons.

And this is not a hacktoberfest PR. I don't like that event, last year I received totally useless PRs in my projects ... nope, this PR is totally self-ish, because I couldn't use the extension without that feature 😝

2020-09-28 03:22 UTC, phucledien approved these changes
Haha @kevinpapst 
That looks good 👍 

Thank you for your PR, hope you will continue contributing in the future

2020-09-28 03:23 UTC, merged

2020-09-28 12:37 UTC, kevinpapst commented
Thanks for approving and merging @phucledien   🎉